import '../models/site_model.dart';

class SiteService {
  Future<List<SiteModel>> mockApiResponse() async {
    await Future.delayed(const Duration(seconds: 2)); // Simulate network delay
    return [
      SiteModel(
        id: '1',
        name: 'Bangalore Logistics Hub',
        location: 'Whitefield',
        managerName: 'Sumit Gupta',
        managerContact: '+91 98765 43210',
        gpsLat: '19.0760° N',
        gpsLng: '72.8777° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '2',
        name: 'Mumbai Port Terminal',
        location: 'JNPT',
        managerName: 'Ananya R.',
        managerContact: '+91 91234 56789',
        gpsLat: '18.5204° N',
        gpsLng: '73.8567° E',
        status: SiteStatus.maintenance,
      ),
      SiteModel(
        id: '3',
        name: 'Delhi Express Center',
        location: 'Okhla',
        managerName: 'Rahul S.',
        managerContact: '+91 87654 32109',
        gpsLat: '13.0827° N',
        gpsLng: '80.2707° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '4',
        name: 'Chennai Distribution Center',
        location: 'Adyar',
        managerName: 'Priya M.',
        managerContact: '+91 99887 76655',
        gpsLat: '12.9716° N',
        gpsLng: '77.5946° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '5',
        name: 'Hyderabad Technology Park',
        location: 'HiTech City',
        managerName: 'Vikram K.',
        managerContact: '+91 94455 66778',
        gpsLat: '9.9312° N',
        gpsLng: '76.2673° E',
        status: SiteStatus.maintenance,
      ),
      SiteModel(
        id: '6',
        name: 'Pune Warehouse',
        location: 'Chakan',
        managerName: 'Sneha P.',
        managerContact: '+91 98001 23456',
        gpsLat: '17.3850° N',
        gpsLng: '78.4867° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '7',
        name: 'Kolkata Fulfillment Center',
        location: 'Howrah',
        managerName: 'Amit D.',
        managerContact: '+91 98001 23456',
        gpsLat: '17.3850° N',
        gpsLng: '78.4867° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '8',
        name: 'Ahmedabad Sorting Hub',
        location: 'Sanand',
        managerName: 'Rishi T.',
        managerContact: '+91 98001 23456',
        gpsLat: '17.3850° N',
        gpsLng: '78.4867° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '9',
        name: 'Jaipur Regional Office',
        location: 'Malviya Nagar',
        managerName: 'Kavita J.',
        managerContact: '+91 98001 23456',
        gpsLat: '17.3850° N',
        gpsLng: '78.4867° E',
        status: SiteStatus.active,
      ),
      SiteModel(
        id: '10',
        name: 'Surat Textile Hub',
        location: 'Varachha',
        managerName: 'Deepak G.',
        managerContact: '+91 98001 23456',
        gpsLat: '17.3850° N',
        gpsLng: '78.4867° E',
        status: SiteStatus.active,
      ),
    ];
  }
}
